import crypto from "node:crypto";
import path from "path";
import fs from "fs-extra";

import type { Installer } from "@/installers/index.js";

export const envVariablesInstaller: Installer = ({
	projectDir,
	packages,
	scopedAppName,
}) => {
	const usingBetterAuth = packages?.betterAuth.inUse;
	const usingSupabase = packages?.supabase.inUse;
	const usingDrizzle = packages?.drizzle.inUse;
	const usingStripe = packages?.stripe.inUse;
	const usingClerk = packages?.clerk.inUse;
	const usingNeon = packages?.neon.inUse;
	const usingVercelAi = packages?.vercelAi.inUse;

	const envContent = getEnvContent(
		!!usingBetterAuth,
		!!usingSupabase,
		!!usingDrizzle,
		!!usingStripe,
		!!usingClerk,
		!!usingNeon,
		!!usingVercelAi,
		scopedAppName,
	);

	const envDest = path.join(projectDir, ".env");

	fs.writeFileSync(envDest, envContent, "utf-8");
};

const getEnvContent = (
	usingBetterAuth: boolean,
	usingSupabase: boolean,
	usingDrizzle: boolean,
	usingStripe: boolean,
	usingClerk: boolean,
	usingNeon: boolean,
	usingVercelAi: boolean,
	scopedAppName: string,
) => {
	let content = `
# Base variables
NEXT_PUBLIC_BASE_URL="http://localhost:3000"
GOOGLE_ANALYTICS_TAG="G-xxxxxxx" # Google Analytics G-Tag ID \n`;

	if (usingBetterAuth) {
		const secret = Buffer.from(
			crypto.getRandomValues(new Uint8Array(32)),
		).toString("base64");

		content += `
# Better Auth
BETTER_AUTH_SECRET="${secret}" # Generated by next-ts-cli.

# Better Auth GitHub OAuth
BETTER_AUTH_GITHUB_CLIENT_ID=""
BETTER_AUTH_GITHUB_CLIENT_SECRET=""
\n`;
	}

	if (usingSupabase)
		content += `
# Supabase
# https://supabase.com/docs/guides/functions/secrets
NEXT_PUBLIC_SUPABASE_URL="https://<app-id>.supabase.co", 
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY="" \n`;

	if (usingDrizzle) content += "# Drizzle";
	if (usingNeon) content += " + Neon";

	content += "\n";

	if (usingDrizzle || usingNeon) {
		content += `DATABASE_URL="postgresql://postgres:password@localhost:5432/${scopedAppName}" \n`;
	}

	if (usingStripe) {
		content += `
# https://dashboard.stripe.com/apikeys

NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=""
STRIPE_SECRET_KEY=""
STRIPE_WEBHOOK_SECRET=""\n`;
	}

	if (usingClerk) {
		content += `
# Clerk
# https://clerk.com/docs/nextjs/getting-started/quickstart
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="pk_test_..."
CLERK_SECRET_KEY="sk_test_..."\n
`;
	}

	if (usingVercelAi) {
		content += `
# Vercel AI Gateway
# https://ai-sdk.dev/docs/getting-started/nextjs-app-router
AI_GATEWAY_API_KEY="sk_..." \n`;
	}

	return content;
};
